version: '3'

# Автоматическая загрузка переменных из .env
dotenv: ['.env']

# Глобальные переменные проекта
vars:
  BIN_DIR: '{{.ROOT_DIR}}/bin'

  GOOSE: '{{.BIN_DIR}}/goose'
  GOOSE_VERSION: 'v3.14.0'
  
  MOCKERY_VERSION: 'v2.53.3'
  MOCKERY: "{{.BIN_DIR}}/mockery"
  
  COVERAGE_DIR: '{{.ROOT_DIR}}/coverage'

tasks:
  install-deps:
    desc: '📦 Устанавливает goose в ./bin'
    cmds:
      - |
        [ -f {{.GOOSE}} ] || {
          echo '📦 Installing goose...'
          GOBIN={{.BIN_DIR}} go install github.com/pressly/goose/v3/cmd/goose@{{.GOOSE_VERSION}}
        }
    status:
      - test -x {{.GOOSE}}

  # ========================
  # MIGRATIONS (MAIN DB)
  # ========================

  local-migration-status:
    desc: '🔍 Показать статус миграций основной БД'
    deps: [ install-deps ]
    cmds:
      - '{{.GOOSE}} -dir ${MIGRATION_DIR} postgres ${PG_DSN} status -v'

  local-migration-up:
    desc: '⬆️ Применить миграции основной БД'
    deps: [ install-deps ]
    cmds:
      - '{{.GOOSE}} -dir ${MIGRATION_DIR} postgres ${PG_DSN} up -v'

  local-migration-down:
    desc: '⬇️ Откатить последнюю миграцию основной БД'
    deps: [ install-deps ]
    cmds:
      - '{{.GOOSE}} -dir ${MIGRATION_DIR} postgres ${PG_DSN} down -v'

  # ========================
  # MOCKS & TEST COVERAGE
  # ========================

  mockery:install:
    desc: "Устанавливает mockery в ./bin"
    cmds:
      - |
        [ -f {{.MOCKERY}} ] || {
          echo '📦 Installing mockery...'
          GOBIN={{.BIN_DIR}} go install github.com/vektra/mockery/v2@{{.MOCKERY_VERSION}}
        }
    status:
      - test -x {{.MOCKERY}}

  mockery:gen:
    desc: "Генерирует моки интерфейсов с помощью mockery"
    deps: [ mockery:install ]
    cmds:
      - |
        echo '🧪 Генерация моков...'
        {{.MOCKERY}}

  test-coverage:
    desc: "Тесты с покрытием бизнес-логики, автоматический поиск и анализ всех модулей"
    cmds:
      - |
        echo "🧪 Запускаем расчёт покрытия..."
        rm -rf {{.COVERAGE_DIR}}
        mkdir -p {{.COVERAGE_DIR}}
        
        # Находим все пакеты, для которых нужно измерить покрытие (исключаем mocks)
        TARGET_PACKAGES=$(go list ./internal/... | grep -v "/mocks" | grep -E '/(api|service)/' | tr '\n' ',')
        
        if [ -z "$TARGET_PACKAGES" ]; then
          echo "⚠️ Не найдено пакетов для тестирования"
          exit 1
        fi
        
        echo "🧪 Запуск тестов со сбором покрытия для всех модулей..."
        go test -v -coverprofile={{.COVERAGE_DIR}}/coverage.out -coverpkg=$TARGET_PACKAGES ./...
        
        echo "🧾 Общее покрытие:"
        go tool cover -func={{.COVERAGE_DIR}}/coverage.out | tail -n1

  coverage:html:
    desc: "Генерирует HTML-отчёт покрытия и открывает его в браузере"
    deps: [ test-coverage ]
    cmds:
      - |
        OUTPUT={{.COVERAGE_DIR}}/coverage.html
        echo "🌐 Генерируем HTML-отчёт..."
        go tool cover -html={{.COVERAGE_DIR}}/coverage.out -o $OUTPUT

        echo "🚀 Открываем $OUTPUT"
        if command -v open &> /dev/null; then
          open $OUTPUT  # macOS
        elif command -v xdg-open &> /dev/null; then
          xdg-open $OUTPUT  # Linux
        else
          echo "📂 Отчёт сохранён в $OUTPUT (открой вручную)"
        fi
